# Generated by Django 2.2.6 on 2020-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200319_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('0', '未知'), ('2', '女')], default='0', max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='type',
            field=models.CharField(choices=[(0, '管理员'), (1, '普通用户')], default='1', max_length=2, verbose_name='类型'),
        ),
    ]
